# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200, null=True)),
                ('dob', models.DateField(max_length=8)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_name', models.CharField(max_length=200, null=True)),
                ('date_released', models.DateField(null=True)),
                ('season', models.IntegerField(null=True)),
                ('episode_review', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=200, null=True)),
                ('movie_description', models.CharField(max_length=200, null=True)),
                ('movie_rating', models.IntegerField(null=True)),
                ('release_date', models.DateField(max_length=8, null=True)),
                ('movie_review', models.CharField(max_length=200, null=True)),
                ('movie_logo', models.ImageField(null=True, upload_to='')),
                ('actors', models.ManyToManyField(to='forms.Actors')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Genres')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=200, null=True)),
                ('series_desc', models.CharField(max_length=200, null=True)),
                ('series_rating', models.IntegerField(null=True)),
                ('release_date', models.DateField(max_length=8, null=True)),
                ('General_review', models.CharField(max_length=200, null=True)),
                ('series_logo', models.ImageField(null=True, upload_to='')),
                ('actors', models.ManyToManyField(to='forms.Actors')),
                ('series_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Genres')),
            ],
        ),
        migrations.AddField(
            model_name='episode',
            name='ser_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.Series'),
        ),
    ]
