# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_review',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_review',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='General_review',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_desc',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
