# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-01 13:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20170725_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='logo_url',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
